### ISSUE TITLE
thread 'main' panicked

### ISSUE THREAD

**Issue by Its-Just-Nans** [ystero-dev/hampi#116] opened 2024-04-26 14:27 UTC
hello,

I tried running hampi against this freshly exported x2ap specification: 

https://github.com/tramex/types_lte_3gpp/blob/main/asn/36.423_spec_X2AP.asn

You can test by using this command this the repo

```sh
cargo run -- --codec uper --module code.re -- 36.423_spec_X2AP.asn
```

but I ended up having this error

```txt
thread 'main' panicked at asn-compiler/src/resolver/asn/values.rs:28:66:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is that normal ?

**Comment by Its-Just-Nans** [comment] 2024-04-26 15:46
Also with https://github.com/tramex/types_lte_3gpp/blob/main/asn/36.413_spec_S1AP.asn

```txt
Error: Custom { kind: InvalidInput, error: "Compilation Error: Resolve: Referenced Type for 'CSGMembershipStatus' Not resolved yet!" }
```

**Comment by gabhijit** [comment] 2024-04-26 18:05
> hello,
> 
> I tried running hampi against this freshly exported x2ap specification:
> 
> https://github.com/tramex/types_lte_3gpp/blob/main/asn/36.423_spec_X2AP.asn
> 
> You can test by using this command this the repo
> 
> ```shell
> cargo run -- --codec uper --module code.re -- 36.423_spec_X2AP.asn
> ```
> 
> but I ended up having this error
> 
> ```
> thread 'main' panicked at asn-compiler/src/resolver/asn/values.rs:28:66:
> called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Is that normal ?

This is very likely a bug in the compiler - some unhandled construct. Will take a look at this.

**Comment by gabhijit** [comment] 2024-04-26 18:08
> Also with https://github.com/tramex/types_lte_3gpp/blob/main/asn/36.413_spec_S1AP.asn
> 
> ```
> Error: Custom { kind: InvalidInput, error: "Compilation Error: Resolve: Referenced Type for 'CSGMembershipStatus' Not resolved yet!" }
> ```

This looks like symbol resolution issue most likely due to the dependency not being compiled. 
For any protocol, you will generally have to use ALL files that are dependent on each other for those to be compiled successfully. For S1AP we have been able to successfully compile this. Please take a look [here](https://github.com/ystero-dev/hampi/tree/master/examples/specs/s1ap) for how it is done. 

This is not related to the issue above most likely.

**Comment by gabhijit** [comment] 2024-04-28 04:00
> > hello,
> > I tried running hampi against this freshly exported x2ap specification:
> > https://github.com/tramex/types_lte_3gpp/blob/main/asn/36.423_spec_X2AP.asn
> > You can test by using this command this the repo
> > ```shell
> > cargo run -- --codec uper --module code.re -- 36.423_spec_X2AP.asn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but I ended up having this error
> > ```
> > thread 'main' panicked at asn-compiler/src/resolver/asn/values.rs:28:66:
> > called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
> > note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is that normal ?
> 
> This is very likely a bug in the compiler - some unhandled construct. Will take a look at this.

I am trying to reproduce this, but I am not able to reproduce it. Following is my command line - 

```shell
cargo run --bin hampi-rs-asn1c -- --codec uper --module code.re -- x2ap.asn
```
I keep getting one of the two errors. I believe this problem is due to both 
`id-CSGMembershipStatus` and `CSGMembershipStatus` not being there in the `IMPORTS` section of the ASN.1 Spec file. 

That is the likely cause.

**Comment by Its-Just-Nans** [comment] 2024-05-29 08:03
Hi
thanks for your answer

Looks like some defiinitions have been renamed but not all

I needed to manual patch some asn file : https://github.com/tramex/types_lte_3gpp/blob/ddee7577a293211aabb0e3f6b6eb078b550c2b3f/build.py#L40


I have now a compiled s1ap. Now working on x2ap


I've made #119 to have a clearer error


Will update the thread when I have a working x2ap

**Comment by Its-Just-Nans** [comment] 2024-05-29 08:15
Turns out the patch is the same for x2ap

I've made a second PR #120 to add some error handling :)

**Comment by gabhijit** [comment] 2024-05-29 09:29
Both #119 and #120 are merged. You may want to close this issue if you think nothing needs to be addressed.

**Closed** 2024-05-29 09:35 UTC
